### PR TITLE
fix #570: use .get() to check for bid & ask values

### LINKED ISSUE #570: django.utils.datastructures:MultiValueDictKeyError: "'offer'"
At File "/app/auctions/views.py", line 90, in post

Full New Relic traceback:
```

Traceback (most recent call last):
File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 180, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 482, in manage_workers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 548, in spawn_workers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 119, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 66, in run_for_one
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/dj_static.py", line 83, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 872, in wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
File "/app/auctions/views.py", line 90, in post
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
```

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

File: static/js/widget-app.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ class WidgetApp {
             return false
         }
 
-        if (diff === 0){
+        if (diff === 0 || diff === NaN){
```
Comment (jdungan) [inline static/js/widget-app.js]: NaN === NaN is false... WAT!

**Comment by jdungan** [comment]
The javascript now works, but I cannot test the submit. If you can test my change I think this is good to merge.

**Comment by groovecoder** [comment]
Works. Good to go.
